export interface SignalConfidenceInfo {
  confidence: number;
  timeframes: string[];
  category: string;
}

export const SignalConfidence: Record<string, SignalConfidenceInfo> = {
  // Candlestick Patterns
  engulfing_bullish: { confidence: 75, timeframes: ['short', 'mid', 'long'], category: 'Candlestick Patterns' },
  engulfing_bearish: { confidence: 75, timeframes: ['short', 'mid', 'long'], category: 'Candlestick Patterns' },
  hammer: { confidence: 72, timeframes: ['mid', 'long'], category: 'Candlestick Patterns' },
  shooting_star: { confidence: 72, timeframes: ['mid', 'long'], category: 'Candlestick Patterns' },
  doji_reversal: { confidence: 65, timeframes: ['short', 'mid', 'long'], category: 'Candlestick Patterns' },
  morning_star: { confidence: 78, timeframes: ['mid', 'long'], category: 'Candlestick Patterns' },
  evening_star: { confidence: 78, timeframes: ['mid', 'long'], category: 'Candlestick Patterns' },
  three_white_soldiers: { confidence: 80, timeframes: ['mid', 'long'], category: 'Candlestick Patterns' },
  three_black_crows: { confidence: 80, timeframes: ['mid', 'long'], category: 'Candlestick Patterns' },
  piercing_pattern: { confidence: 70, timeframes: ['mid', 'long'], category: 'Candlestick Patterns' },
  dark_cloud_cover: { confidence: 70, timeframes: ['mid', 'long'], category: 'Candlestick Patterns' },
  tweezer_top: { confidence: 68, timeframes: ['short', 'mid'], category: 'Candlestick Patterns' },
  tweezer_bottom: { confidence: 68, timeframes: ['short', 'mid'], category: 'Candlestick Patterns' },
  marubozu_bullish: { confidence: 73, timeframes: ['short', 'mid'], category: 'Candlestick Patterns' },
  marubozu_bearish: { confidence: 73, timeframes: ['short', 'mid'], category: 'Candlestick Patterns' },
  harami_bullish: { confidence: 70, timeframes: ['mid', 'long'], category: 'Candlestick Patterns' },
  harami_bearish: { confidence: 70, timeframes: ['mid', 'long'], category: 'Candlestick Patterns' },
  inverted_hammer: { confidence: 71, timeframes: ['mid', 'long'], category: 'Candlestick Patterns' },
  hanging_man: { confidence: 71, timeframes: ['mid', 'long'], category: 'Candlestick Patterns' },

  // Moving Averages
  ma_cross_golden: { confidence: 82, timeframes: ['mid', 'long'], category: 'Moving Averages' },
  ma_cross_death: { confidence: 82, timeframes: ['mid', 'long'], category: 'Moving Averages' },
  price_above_ma20: { confidence: 70, timeframes: ['short', 'mid'], category: 'Moving Averages' },
  price_below_ma20: { confidence: 70, timeframes: ['short', 'mid'], category: 'Moving Averages' },
  ma_ribbon_bullish: { confidence: 76, timeframes: ['mid', 'long'], category: 'Moving Averages' },
  ma_ribbon_bearish: { confidence: 76, timeframes: ['mid', 'long'], category: 'Moving Averages' },
  ema_cross_fast: { confidence: 74, timeframes: ['short', 'mid'], category: 'Moving Averages' },
  triple_ema_bullish: { confidence: 78, timeframes: ['mid'], category: 'Moving Averages' },
  triple_ema_bearish: { confidence: 78, timeframes: ['mid'], category: 'Moving Averages' },

  // Momentum Indicators
  rsi_oversold: { confidence: 68, timeframes: ['short', 'mid', 'long'], category: 'Momentum Indicators' },
  rsi_overbought: { confidence: 68, timeframes: ['short', 'mid', 'long'], category: 'Momentum Indicators' },
  rsi_divergence_bullish: { confidence: 85, timeframes: ['mid', 'long'], category: 'Momentum Indicators' },
  rsi_divergence_bearish: { confidence: 85, timeframes: ['mid', 'long'], category: 'Momentum Indicators' },
  rsi_centerline_cross_up: { confidence: 72, timeframes: ['mid'], category: 'Momentum Indicators' },
  rsi_centerline_cross_down: { confidence: 72, timeframes: ['mid'], category: 'Momentum Indicators' },
  macd_cross_bullish: { confidence: 79, timeframes: ['mid', 'long'], category: 'Momentum Indicators' },
  macd_cross_bearish: { confidence: 79, timeframes: ['mid', 'long'], category: 'Momentum Indicators' },
  macd_divergence_bullish: { confidence: 87, timeframes: ['mid', 'long'], category: 'Momentum Indicators' },
  macd_divergence_bearish: { confidence: 87, timeframes: ['mid', 'long'], category: 'Momentum Indicators' },
  macd_histogram_reversal_bullish: { confidence: 75, timeframes: ['short', 'mid'], category: 'Momentum Indicators' },
  macd_histogram_reversal_bearish: { confidence: 75, timeframes: ['short', 'mid'], category: 'Momentum Indicators' },
  stoch_oversold: { confidence: 66, timeframes: ['short', 'mid'], category: 'Momentum Indicators' },
  stoch_overbought: { confidence: 66, timeframes: ['short', 'mid'], category: 'Momentum Indicators' },
  stoch_cross_bullish: { confidence: 71, timeframes: ['short', 'mid'], category: 'Momentum Indicators' },
  stoch_cross_bearish: { confidence: 71, timeframes: ['short', 'mid'], category: 'Momentum Indicators' },
  cci_oversold: { confidence: 67, timeframes: ['short', 'mid'], category: 'Momentum Indicators' },
  cci_overbought: { confidence: 67, timeframes: ['short', 'mid'], category: 'Momentum Indicators' },
  williams_r_oversold: { confidence: 65, timeframes: ['short', 'mid'], category: 'Momentum Indicators' },
  williams_r_overbought: { confidence: 65, timeframes: ['short', 'mid'], category: 'Momentum Indicators' },
  momentum_5: { confidence: 72, timeframes: ['short', 'mid'], category: 'Momentum Indicators' },
  momentum_10: { confidence: 74, timeframes: ['short', 'mid'], category: 'Momentum Indicators' },
  mfi_oversold: { confidence: 73, timeframes: ['short', 'mid', 'long'], category: 'Momentum Indicators' },
  mfi_overbought: { confidence: 73, timeframes: ['short', 'mid', 'long'], category: 'Momentum Indicators' },
  mfi_divergence_bullish: { confidence: 82, timeframes: ['mid', 'long'], category: 'Momentum Indicators' },
  mfi_divergence_bearish: { confidence: 82, timeframes: ['mid', 'long'], category: 'Momentum Indicators' },
  roc_bullish: { confidence: 70, timeframes: ['short', 'mid'], category: 'Momentum Indicators' },
  roc_bearish: { confidence: 70, timeframes: ['short', 'mid'], category: 'Momentum Indicators' },
  tsi_cross_bullish: { confidence: 76, timeframes: ['mid', 'long'], category: 'Momentum Indicators' },
  tsi_cross_bearish: { confidence: 76, timeframes: ['mid', 'long'], category: 'Momentum Indicators' },

  // Volume Analysis
  volume_spike_bullish: { confidence: 77, timeframes: ['short', 'mid', 'long'], category: 'Volume Analysis' },
  volume_spike_bearish: { confidence: 77, timeframes: ['short', 'mid', 'long'], category: 'Volume Analysis' },
  volume_divergence_bullish: { confidence: 81, timeframes: ['mid', 'long'], category: 'Volume Analysis' },
  volume_divergence_bearish: { confidence: 81, timeframes: ['mid', 'long'], category: 'Volume Analysis' },
  obv_bullish: { confidence: 74, timeframes: ['mid', 'long'], category: 'Volume Analysis' },
  obv_bearish: { confidence: 74, timeframes: ['mid', 'long'], category: 'Volume Analysis' },
  vwap_cross_above: { confidence: 76, timeframes: ['short', 'mid'], category: 'Volume Analysis' },
  vwap_cross_below: { confidence: 76, timeframes: ['short', 'mid'], category: 'Volume Analysis' },
  accumulation_distribution_bullish: { confidence: 73, timeframes: ['mid', 'long'], category: 'Volume Analysis' },
  accumulation_distribution_bearish: { confidence: 73, timeframes: ['mid', 'long'], category: 'Volume Analysis' },
  cmf_bullish: { confidence: 75, timeframes: ['mid', 'long'], category: 'Volume Analysis' },
  cmf_bearish: { confidence: 75, timeframes: ['mid', 'long'], category: 'Volume Analysis' },
  volume_climax_bullish: { confidence: 79, timeframes: ['short', 'mid', 'long'], category: 'Volume Analysis' },
  volume_climax_bearish: { confidence: 79, timeframes: ['short', 'mid', 'long'], category: 'Volume Analysis' },

  // Volatility Indicators
  bollinger_squeeze: { confidence: 80, timeframes: ['short', 'mid', 'long'], category: 'Volatility Indicators' },
  bollinger_breakout_up: { confidence: 78, timeframes: ['short', 'mid'], category: 'Volatility Indicators' },
  bollinger_breakout_down: { confidence: 78, timeframes: ['short', 'mid'], category: 'Volatility Indicators' },
  bollinger_bounce_up: { confidence: 69, timeframes: ['short', 'mid'], category: 'Volatility Indicators' },
  bollinger_bounce_down: { confidence: 69, timeframes: ['short', 'mid'], category: 'Volatility Indicators' },
  atr_expansion: { confidence: 71, timeframes: ['short', 'mid'], category: 'Volatility Indicators' },
  keltner_breakout_up: { confidence: 75, timeframes: ['mid'], category: 'Volatility Indicators' },
  keltner_breakout_down: { confidence: 75, timeframes: ['mid'], category: 'Volatility Indicators' },
  donchian_breakout_up: { confidence: 77, timeframes: ['mid', 'long'], category: 'Volatility Indicators' },
  donchian_breakout_down: { confidence: 77, timeframes: ['mid', 'long'], category: 'Volatility Indicators' },

  // Trend Indicators
  adx_strong_trend: { confidence: 79, timeframes: ['mid', 'long'], category: 'Trend Indicators' },
  adx_weak_trend: { confidence: 70, timeframes: ['mid', 'long'], category: 'Trend Indicators' },
  adx_reversal: { confidence: 76, timeframes: ['mid', 'long'], category: 'Trend Indicators' },
  supertrend_bullish: { confidence: 81, timeframes: ['mid', 'long'], category: 'Trend Indicators' },
  supertrend_bearish: { confidence: 81, timeframes: ['mid', 'long'], category: 'Trend Indicators' },
  parabolic_sar_flip_bullish: { confidence: 74, timeframes: ['mid', 'long'], category: 'Trend Indicators' },
  parabolic_sar_flip_bearish: { confidence: 74, timeframes: ['mid', 'long'], category: 'Trend Indicators' },
  ichimoku_bullish: { confidence: 83, timeframes: ['long'], category: 'Trend Indicators' },
  ichimoku_bearish: { confidence: 83, timeframes: ['long'], category: 'Trend Indicators' },
  aroon_bullish: { confidence: 75, timeframes: ['mid', 'long'], category: 'Trend Indicators' },
  aroon_bearish: { confidence: 75, timeframes: ['mid', 'long'], category: 'Trend Indicators' },
  elder_ray_bullish: { confidence: 74, timeframes: ['mid', 'long'], category: 'Trend Indicators' },
  elder_ray_bearish: { confidence: 74, timeframes: ['mid', 'long'], category: 'Trend Indicators' },

  // Price Action & Structure
  higher_high: { confidence: 77, timeframes: ['short', 'mid', 'long'], category: 'Price Action & Structure' },
  lower_low: { confidence: 77, timeframes: ['short', 'mid', 'long'], category: 'Price Action & Structure' },
  break_of_structure_bullish: { confidence: 84, timeframes: ['short', 'mid', 'long'], category: 'Price Action & Structure' },
  break_of_structure_bearish: { confidence: 84, timeframes: ['short', 'mid', 'long'], category: 'Price Action & Structure' },
  support_bounce: { confidence: 72, timeframes: ['short', 'mid', 'long'], category: 'Price Action & Structure' },
  resistance_rejection: { confidence: 72, timeframes: ['short', 'mid', 'long'], category: 'Price Action & Structure' },
  support_break: { confidence: 80, timeframes: ['short', 'mid', 'long'], category: 'Price Action & Structure' },
  resistance_break: { confidence: 80, timeframes: ['short', 'mid', 'long'], category: 'Price Action & Structure' },
  pivot_point_bullish: { confidence: 69, timeframes: ['short', 'mid'], category: 'Price Action & Structure' },
  pivot_point_bearish: { confidence: 69, timeframes: ['short', 'mid'], category: 'Price Action & Structure' },
  fibonacci_bounce_382: { confidence: 73, timeframes: ['mid', 'long'], category: 'Price Action & Structure' },
  fibonacci_bounce_618: { confidence: 76, timeframes: ['mid', 'long'], category: 'Price Action & Structure' },
  round_number_support: { confidence: 68, timeframes: ['short', 'mid', 'long'], category: 'Price Action & Structure' },
  round_number_resistance: { confidence: 68, timeframes: ['short', 'mid', 'long'], category: 'Price Action & Structure' },
  gap_up: { confidence: 76, timeframes: ['mid', 'long'], category: 'Price Action & Structure' },
  gap_down: { confidence: 76, timeframes: ['mid', 'long'], category: 'Price Action & Structure' },
  order_block_bullish: { confidence: 78, timeframes: ['short', 'mid', 'long'], category: 'Price Action & Structure' },
  order_block_bearish: { confidence: 78, timeframes: ['short', 'mid', 'long'], category: 'Price Action & Structure' },
  fvg_bullish: { confidence: 77, timeframes: ['short', 'mid', 'long'], category: 'Price Action & Structure' },
  fvg_bearish: { confidence: 77, timeframes: ['short', 'mid', 'long'], category: 'Price Action & Structure' },
  liquidity_sweep_bullish: { confidence: 80, timeframes: ['short', 'mid', 'long'], category: 'Price Action & Structure' },
  liquidity_sweep_bearish: { confidence: 80, timeframes: ['short', 'mid', 'long'], category: 'Price Action & Structure' },
  choch_bullish: { confidence: 79, timeframes: ['short', 'mid', 'long'], category: 'Price Action & Structure' },
  choch_bearish: { confidence: 79, timeframes: ['short', 'mid', 'long'], category: 'Price Action & Structure' },
  premium_zone: { confidence: 71, timeframes: ['mid', 'long'], category: 'Price Action & Structure' },
  discount_zone: { confidence: 71, timeframes: ['mid', 'long'], category: 'Price Action & Structure' },

  // Volume Profile
  poc_support: { confidence: 75, timeframes: ['mid', 'long'], category: 'Volume Profile' },
  poc_resistance: { confidence: 75, timeframes: ['mid', 'long'], category: 'Volume Profile' },
  value_area_high: { confidence: 72, timeframes: ['mid', 'long'], category: 'Volume Profile' },
  value_area_low: { confidence: 72, timeframes: ['mid', 'long'], category: 'Volume Profile' },
  high_volume_node: { confidence: 73, timeframes: ['mid', 'long'], category: 'Volume Profile' },
  low_volume_node: { confidence: 70, timeframes: ['mid', 'long'], category: 'Volume Profile' },
};

export const TIMEFRAME_MINUTES: Record<string, number> = {
  '1m': 1,
  '3m': 3,
  '5m': 5,
  '15m': 15,
  '30m': 30,
  '1h': 60,
  '2h': 120,
  '4h': 240,
  '6h': 360,
  '8h': 480,
  '12h': 720,
  '1d': 1440,
  '3d': 4320,
  '1w': 10080,
};